on:
  pull_request:
    branches:
      - main
  
jobs:
  read_env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read environment variable
        run: |
          echo ${{ env.local }}
          echo ${{ secrets.supersecret }}
